version: '3'

services:
  vue-app-lesson04:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    tty: true
    environment:
      - NODE_ENV=development

